els-ASAP auto commit file/tag kpatch-0.6.1-1.el7.src.rpm

diff --git a/src/test/integration/kpatch-test b/src/test/integration/kpatch-test
--- a/src/test/integration/kpatch-test
+++ b/src/test/integration/kpatch-test
@@ -133,9 +133,8 @@ unload_all() {
 build_module() {
 	file=$1
 	prefix=$(basename ${file%%.patch})
-	module=kpatch-$prefix.ko
-
-	[[ $prefix = COMBINED ]] && return
+	modname="test-$prefix"
+	module="${modname}.ko"
 
 	if [[ $prefix =~ -FAIL ]]; then
 		shouldfail=1
@@ -152,7 +151,7 @@ build_module() {
 
 	log "build: $prefix"
 
-	if ! $KPATCHBUILD $file >> $LOG 2>&1; then
+	if ! $KPATCHBUILD -n $modname $file >> $LOG 2>&1; then
 		[[ $shouldfail -eq 0 ]] && error "$prefix: build failed"
 	else
 		[[ $shouldfail -eq 1 ]] && error "$prefix: build succeeded when it should have failed"
@@ -162,10 +161,10 @@ build_module() {
 run_load_test() {
 	file=$1
 	prefix=$(basename ${file%%.patch})
-	module=kpatch-$prefix.ko
+	modname="test-$prefix"
+	module="${modname}.ko"
 	testprog="$(dirname $1)/$prefix-LOADED.test"
 
-	[[ $prefix = COMBINED ]] && return
 	[[ $prefix =~ -FAIL ]] && return
 
 	if [[ ! -e $module ]]; then
@@ -220,14 +219,8 @@ run_custom_test() {
 
 build_combined_module() {
 
-	if [[ $SKIPBUILD -eq 1 ]] && [[ -e kpatch-COMBINED.ko ]]; then
+	if [[ $SKIPBUILD -eq 1 ]] && [[ -e test-COMBINED.ko ]]; then
 		log "skipping build: combined"
-		return
-	fi
-
-	if ! which combinediff > /dev/null; then
-		log "patchutils not installed, skipping combined module build"
-		error "PLEASE INSTALL PATCHUTILS"
 		return
 	fi
 
@@ -242,37 +235,16 @@ build_combined_module() {
 		return
 	fi
 
-	rm -f COMBINED.patch TMP.patch
-	first=1
-	for file in "${COMBINED_LIST[@]}"; do
-		prefix=${file%%.patch}
-
-		log "combine: $prefix"
-
-		if [[ $first -eq 1 ]]; then
-			cp -f $file COMBINED.patch
-			first=0
-			continue
-		fi
-
-		combinediff COMBINED.patch $file > TMP.patch
-		mv -f TMP.patch COMBINED.patch
-	done
-
 	log "build: combined module"
 
-	if ! $KPATCHBUILD COMBINED.patch >> $LOG 2>&1; then
+	if ! $KPATCHBUILD -n test-COMBINED "${COMBINED_LIST[@]}" >> $LOG 2>&1; then
 		error "combined build failed"
 	fi
 }
 
 run_combined_test() {
-	if [[ ! -e COMBINED.patch ]]; then
-		return
-	fi
-
-	if [[ ! -e kpatch-COMBINED.ko ]]; then
-		log "can't find kpatch-COMBINED.ko, skipping"
+	if [[ ! -e test-COMBINED.ko ]]; then
+		log "can't find test-COMBINED.ko, skipping"
 		return
 	fi
 
@@ -288,7 +260,7 @@ run_combined_test() {
 		fi
 	done
 
-	if ! $KPATCH load kpatch-COMBINED.ko >> $LOG 2>&1; then
+	if ! $KPATCH load test-COMBINED.ko >> $LOG 2>&1; then
 		error "combined: kpatch load failed"
 		return
 	fi
@@ -300,7 +272,7 @@ run_combined_test() {
 		fi
 	done
 
-	if ! $KPATCH unload kpatch-COMBINED.ko >> $LOG 2>&1; then
+	if ! $KPATCH unload test-COMBINED.ko >> $LOG 2>&1; then
 		error "combined: kpatch unload failed"
 		return
 	fi
